"""Prefer PySide6; use the distro-provided PyQt6 fallback when PySide6 is incomplete."""

try:
    from PySide6.QtCore import QLockFile, Qt, QTimer
    from PySide6.QtGui import QColor
    from PySide6.QtWidgets import (  # type: ignore[import-not-found]
        QAbstractItemView,
        QAbstractSpinBox,
        QApplication,
        QCheckBox,
        QComboBox,
        QDialog,
        QDialogButtonBox,
        QFileDialog,
        QFormLayout,
        QFrame,
        QGraphicsDropShadowEffect,
        QHBoxLayout,
        QHeaderView,
        QLabel,
        QLineEdit,
        QListWidget,
        QMainWindow,
        QMessageBox,
        QProgressBar,
        QPushButton,
        QScrollArea,
        QSpinBox,
        QSplitter,
        QStackedWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QVBoxLayout,
        QWidget,
    )

    BINDING = "PySide6"
except ModuleNotFoundError:
    from PyQt6.QtCore import QLockFile, Qt, QTimer
    from PyQt6.QtGui import QColor
    from PyQt6.QtWidgets import (
        QAbstractItemView,
        QAbstractSpinBox,
        QApplication,
        QCheckBox,
        QComboBox,
        QDialog,
        QDialogButtonBox,
        QFileDialog,
        QFormLayout,
        QFrame,
        QGraphicsDropShadowEffect,
        QHBoxLayout,
        QHeaderView,
        QLabel,
        QLineEdit,
        QListWidget,
        QMainWindow,
        QMessageBox,
        QProgressBar,
        QPushButton,
        QScrollArea,
        QSpinBox,
        QSplitter,
        QStackedWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QVBoxLayout,
        QWidget,
    )

    BINDING = "PyQt6"

__all__ = [
    "BINDING",
    "QAbstractItemView",
    "QAbstractSpinBox",
    "QApplication",
    "QCheckBox",
    "QComboBox",
    "QDialog",
    "QDialogButtonBox",
    "QFileDialog",
    "QFormLayout",
    "QFrame",
    "QHBoxLayout",
    "QHeaderView",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QLockFile",
    "QMainWindow",
    "QMessageBox",
    "QProgressBar",
    "QGraphicsDropShadowEffect",
    "QPushButton",
    "QScrollArea",
    "QSpinBox",
    "QSplitter",
    "QStackedWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QTextEdit",
    "QTimer",
    "QVBoxLayout",
    "QWidget",
    "QColor",
    "Qt",
]
